CREATE TABLE [Image](
	Id INT IDENTITY(1, 1) NOT NULL,
	Original VARBINARY(MAX) NULL,
	Preview VARBINARY(MAX) NULL,
	IsValid BIT NOT NULL,
	CreatedByUserId INT NOT NULL,
	CreatedDateTime DATETIME NOT NULL,
	CONSTRAINT PK_Image PRIMARY KEY(Id)
)