CREATE TABLE DishType(
	Id INT IDENTITY(1, 1) NOT NULL,
	Name NVARCHAR(256) NOT NULL,
	IsValid BIT NOT NULL DEFAULT 1,
	CreatedByUserId INT NOT NULL,
	CreatedDateTime DATETIME NOT NULL,
	CONSTRAINT PK_DishType PRIMARY KEY(Id)
)

EXEC FK 'DishType', 'CreatedByUserId', 'User'