CREATE TABLE Place(
	Id INT IDENTITY(1, 1) NOT NULL,
	GId NVARCHAR(40) NOT NULL,
	Name NVARCHAR(256) NOT NULL,
	[Address] NVARCHAR(128) NOT NULL,
	Lat NVARCHAR(16) NOT NULL,
	Lng NVARCHAR(16) NOT NULL,
	IsValid BIT NOT NULL,
	CreatedByUserId INT NOT NULL,
	CreatedDateTime DATETIME NOT NULL,
	CONSTRAINT PK_Place PRIMARY KEY(Id)
)


EXEC FK 'Place', 'CreatedByUserId', 'User'