//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Batonezas.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishReview
    {
        public int Id { get; set; }
        public int ReviewId { get; set; }
        public int DishId { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Review Review { get; set; }
    }
}
