//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Batonezas.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlacePlaceType
    {
        public int Id { get; set; }
        public int PlaceId { get; set; }
        public int PlaceTypeId { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual PlaceType PlaceType { get; set; }
    }
}
